### ISSUE TITLE
Incorrect url path used for dataprime log queries

### ISSUE THREAD

**Issue by msitnuboreto** [IBM/logs-go-sdk#8]
**Describe the bug**
It seems an incorrect url path is used for dataprime log queries - the following seems to fix it.

-----------------------------------------------------------------------------

```diff --git a/logsv0/logs_v0_dataprime.go b/logsv0/logs_v0_dataprime.go
index 93ff96a..93cd82f 100644
--- a/logsv0/logs_v0_dataprime.go
+++ b/logsv0/logs_v0_dataprime.go
@@ -69,7 +69,7 @@ func (logs *LogsV0) QueryWithContext(ctx context.Context, queryOptions *QueryOpt
        builder := core.NewRequestBuilder(core.POST)
        builder = builder.WithContext(ctx)
        builder.EnableGzipCompression = logs.GetEnableGzipCompression()
-       _, err = builder.ResolveRequestURL(logs.Service.Options.URL, `/v1/dataprime/query/run`, nil)
+       _, err = builder.ResolveRequestURL(logs.Service.Options.URL, `/v1/query`, nil)
        if err != nil {
                callBack.OnError(err)
                return

```
-----------------------------------------------------------------------------

**To Reproduce**
Replacing the hard coded path "/v1/dataprime/query/run" to "/v1/query" makes the following example code work:
https://github.com/IBM/logs-go-sdk/blob/main/example/v0/example_v0.go

**Expected behavior**
Get a valid response from a call to logsv0.LogsV0.QueryWithContext()

**Comment by bevicted** [comment]
PSA: Fixed by https://github.com/IBM/logs-go-sdk/pull/12
